// nextendo-nx — Nintendo Switch homebrew for the Nextendo Network.
// Copyright (C) 2026 Nextendo Network. PolyForm Shield License 1.0.0.
// Required Notice: Copyright 2026 Nextendo Network
//
// Reviewed C++ port of Prelude's nextendo_hosts_build(). Every functional host
// line (IP + hostname + exact leading spaces) is verbatim from the audited
// production list; only the '#' comment lines were translated to English, and
// the C string-buffer plumbing became std::string. Atmosphère ignores '#' lines,
// so redirect behaviour is unchanged. See RESTRUCTURE.md §4 for the invariants.
//
// NOT COMPILED in the authoring environment (no devkitPro). Logic-reviewed only.
#include "nextendo/hosts.hpp"
#include "nextendo/config.hpp"

namespace nextendo::hosts {

namespace cfg = nextendo::config;

std::string build(const std::string &ip) {
    const std::string nncs2 = cfg::kServerNncs2;
    const std::string mk8   = cfg::kServerMk8Prod;
    std::string o;
    o.reserve(4096);

    auto host = [&](const std::string &lineIp, const char *rest) {
        o += lineIp; o += rest; o += '\n';
    };

    o += "# ============================================================\n";
    o += "#  NEXTENDO NETWORK - Atmosphere DNS-MITM (mode NEXTENDO)\n";
    o += "#  Generated by the Nextendo homebrew. Last matching line wins.\n";
    o += "# ============================================================\n\n";

    o += "# --- 1) All Nintendo -> Nextendo servers ---\n";
    host(ip, "    *.nintendo.com");
    host(ip, "    *.nintendo.co.jp");
    host(ip, " accounts.nintendo.com");
    host(ip, " api.accounts.nintendo.com");
    host(ip, " m-lp1.baas.nintendo.com");
    host(ip, " e0d67c509fb203858ebcb2fe3f88c2aa.baas.nintendo.com");
    host(ip, " cdn-image-e0d67c509fb203858ebcb2fe3f88c2aa.baas.nintendo.com");
    host(ip, " capi.lp1.op2.nintendo.net");
    host(ip, " storage.hac.lp1.scsi.srv.nintendo.net");
    host(ip, " val.hac.penne.srv.nintendo.net");
    host(ip, " god.hac.lp1.penne.srv.nintendo.net");
    host(ip, " dauth-lp1.ndas.srv.nintendo.net");
    host(ip, " aauth.hac.lp1.ndas.srv.nintendo.net");
    // *.srv and *srv (no dot) — the second covers multi-label hosts like
    // g2b309e01-lp1.s.n.srv.nintendo.net that the first does not.
    host(ip, "    *.srv.nintendo.net");
    host(ip, "    *srv.nintendo.net");
    // g2* wildcard covers ALL NEX secure-servers; explicit hosts follow in case a
    // build ignores the mid-label '*'.
    host(ip,   " g2*.s.n.srv.nintendo.net");
    host(mk8,  " g2b309e01-lp1.s.n.srv.nintendo.net"); // MK8 -> production (after wildcard)
    host(ip,   " g23380901-lp1.s.n.srv.nintendo.net"); // SSBU
    host(ip,   " g2ee2e300-lp1.s.n.srv.nintendo.net"); // ACNH
    host(ip,   " g26cfaf00-lp1.s.n.srv.nintendo.net"); // Strikers
    host(ip,   " g20de2100-lp1.s.n.srv.nintendo.net"); // LM3
    host(ip,   " g23932a00-lp1.s.n.srv.nintendo.net"); // Mario Tennis Aces
    host(ip,   " g25c08801-lp1.s.n.srv.nintendo.net"); // ARMS
    host(ip,   " g2df33d01-lp1.s.n.srv.nintendo.net"); // Splatoon 2

    // --- Splatoon 3 / NPLN (gRPC over HTTP/2; no g2* host) ---
    host(ip, " t-dce9377b-lp1.lp1.t.npln.srv.nintendo.net");
    host(ip, " t-adf89f68-lp1.lp1.t.npln.srv.nintendo.net");
    // lp1.nso: the NSO applet. Ends in .nintendo.net, NOT srv — no wildcard covers it.
    host(ip, " lp1.nso.nintendo.net");
    host(ip, " gw.hac.lp1.vermillion.srv.nintendo.net");
    host(ip, " val.hac.lp1.penne.srv.nintendo.net");
    host(ip, " fro-3.hac.lp1.penne.srv.nintendo.net");
    // dragons: ends in .nintendo.net (no generic *.nintendo.net since v3.0.2).
    host(ip, " dragons.hac.lp1.dragons.nintendo.net");
    // gamesync: Splatoon 3 session host (KeepUserSession on TCP/7575). Ends in
    // npln.nintendo.net, NOT srv — *srv does not catch it.
    host(ip, "    *.npln.nintendo.net");
    host(ip, " gamesync.npln.nintendo.net");
    // (*.op2.nintendo.net removed v3.0.2: too broad -> ACNH 2219-4001.)

    // BCAT background content delivery. When the blanket *.nintendo.net was
    // narrowed, *.cdn.nintendo.net fell off and BCAT lives there -> Splatoon 3
    // 2122-2403 (module 122 = bcat). Named, not a wildcard, to avoid re-widening.
    // Our conntest nginx answers 304 here (console reads "nothing to sync" and
    // uses its local cache). NOTE: 304 sends no data; serving real BCAT data is
    // nextendo-bcat-nx's job.
    host(ip, " bcat-list-lp1.cdn.nintendo.net");
    host(ip, " bcat-data-lp1.cdn.nintendo.net");
    host(ip, " bcat-topics-lp1.cdn.nintendo.net");

    // --- Demonware (Crash Team Racing: Nitro-Fueled, Diablo III) ---
    o += "\n# --- Redirect to the private Demonware server (CTR, Diablo III) ---\n";
    host(ip, " demonware.net");
    host(ip, " *.demonware.net");

    o += "\n# --- 2) NAT-check #2: distinct IP from nncs1 (else MK8 test-103) ---\n";
    host(nncs2, "  nncs2-*.n.n.srv.nintendo.net");

    o += "\n# --- 3) ANTI-BAN: telemetry -> our sink, NOT a black hole ---\n";
    // The NSO applet waits SYNCHRONOUSLY for an HTTP response from these before
    // loading lp1.nso. Null-routed, they hang until timeout and the applet gives
    // up. Our sink reads the payload, drops it, and returns 200 immediately:
    // telemetry still never reaches Nintendo, and the applet gets its response.
    host(ip, "          receive-%.dg.srv.nintendo.net");
    host(ip, "          receive-%.er.srv.nintendo.net");

    o += "\n# --- 4) d4c (system update) -> NOT REDIRECTED ---\n";
    o += "# Do not null-route: nim stores a persistent flag.\n\n";

    o += "\n# --- 5) conntest (browser connectivity check) -> Nextendo conntest ---\n";
    o += "# Real Nintendo sometimes blocks conntest -> \"This feature is not available\".\n";
    o += "# We answer X-Organization: Nintendo + 200 OK.\n";
    host(ip, " conntest.nintendowifi.net");
    host(ip, " ctest.cdn.nintendo.net");

    return o;
}

} // namespace nextendo::hosts
