// Prelude — Nintendo Switch homebrew for the Nextendo Network.
// Copyright (C) 2026 Nextendo Network
//
// Licensed under the PolyForm Shield License 1.0.0.
//
// You may use, modify and distribute this software for any purpose EXCEPT providing a product
// that competes with Nextendo Network, or with any product Nextendo Network provides using it.
//
// See LICENSE.md for the full terms, or <https://polyformproject.org/licenses/shield/1.0.0>.
//
// Required Notice: Copyright 2026 Nextendo Network

// ============================================================
//  Prelude — tables de traductions EN / ES / PT / FR / ZH.
//  La langue courante est lue/écrite depuis la SD.
// ============================================================
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <switch.h>

#include "lang.h"

Lang g_lang = LANG_EN;

#define LANG_PATH "sdmc:/switch/prelude_lang.txt"

// --- String tables -------------------------------------------------------
// Each column: EN, ES, PT, FR, ZH.
// Must match StringID enum order exactly.
// Brand names (Nextendo, Nintendo, Prelude) are kept as-is.
static const char *s_strings[STR_COUNT][5] = {
    // --- Picker screen ---
    [STR_TITLE_PRELUDE]      = { "Prelude", "Prelude", "Prelude", "Prelude", "Prelude" },
    [STR_MODE_ACTUAL_PREFIX] = { "Current mode: ", "Modo actual: ", "Modo atual: ", "Mode actuel : ",
                                 "当前模式：" },
    [STR_CURRENT_BADGE]      = { "CURRENT", "ACTUAL", "ATUAL", "ACTUEL",
                                 "当前" },
    [STR_SWITCH_BADGE]       = { "SWITCH HERE", "CAMBIAR AQUI", "MUDAR AQUI", "BASICULER ICI",
                                 "切换到此" },

    // --- Context descriptions ---
    [STR_DESC_NEXTENDO]      = { "Nextendo servers: custom online, icons, friends. Nextendo account required.",
                                 "Servidores Nextendo: online custom, iconos, amigos. Cuenta Nextendo requerida.",
                                 "Servidores Nextendo: online custom, iconos, amigos. Conta Nextendo necessaria.",
                                 "Serveurs Nextendo : online custom, icônes, amis. Compte Nextendo requis.",
                                 "Nextendo 服务器：自定义联机、图标、好友。需要 Nextendo 账号。" },
    [STR_DESC_NINTENDO]      = { "Official Nintendo DNS restored. Telemetry stays blocked.",
                                 "DNS oficial de Nintendo restaurado. La telemetria sigue bloqueada.",
                                 "DNS oficial da Nintendo restaurado. A telemetria continua bloqueada.",
                                 "DNS officiel Nintendo restaure. La telemetrie reste bloquee.",
                                 "恢复 Nintendo 官方 Hosts。遥测仍被屏蔽。" },
    [STR_DESC_S2]            = { "Downloads the Splatoon 2 rotation schedule and installs it into the game.",
                                 "Descarga el calendario de modos de Splatoon 2 y lo instala en el juego.",
                                 "Baixa o calendario de modos do Splatoon 2 e instala no jogo.",
                                 "Télécharge le calendrier des modes de Splatoon 2 et l'installe dans le jeu.",
                                 "下载 Splatoon 2 轮换日程并安装到游戏中。" },

    // --- Help lines ---
    [STR_HELP_MODE]          = { "A: switch mode       < >: change choice       B: quit",
                                 "A: cambiar modo       < >: cambiar eleccion       B: salir",
                                 "A: mudar modo         < >: mudar escolha          B: sair",
                                 "A : changer de mode       < > : changer de choix       B : quitter",
                                 "A: 切换模式       < >: 更换选项       B: 退出" },
    [STR_HELP_S2]            = { "A: install schedule       < >: change choice       B: quit",
                                 "A: instalar horario       < >: cambiar eleccion       B: salir",
                                 "A: instalar cronograma    < >: mudar escolha          B: sair",
                                 "A : installer le planning       < > : changer de choix       B : quitter",
                                 "A: 安装日程       < >: 更换选项       B: 退出" },

    // --- Update banner ---
    [STR_UPDATE_BANNER]      = { "MANDATORY update (v%d.%d.%d)   -   press Y to install",
                                 "Actualizacion OBLIGATORIA (v%d.%d.%d)   -   presiona Y para instalar",
                                 "Atualizacao OBRIGATORIA (v%d.%d.%d)   -   pressione Y para instalar",
                                 "Mise à jour OBLIGATOIRE (v%d.%d.%d)   -   appuie sur Y pour installer",
                                 "必须更新 (v%d.%d.%d)   -   按 Y 安装" },

    // --- Confirm screen ---
    [STR_CONFIRM_NEXTENDO]   = { "Switch to NEXTENDO mode?",
                                 "Pasar a modo NEXTENDO?",
                                 "Mudar para o modo NEXTENDO?",
                                 "Passer en mode NEXTENDO ?",
                                 "切换到 NEXTENDO 模式？" },
    [STR_CONFIRM_NINTENDO]   = { "Switch to NINTENDO mode?",
                                 "Pasar a modo NINTENDO?",
                                 "Mudar para o modo NINTENDO?",
                                 "Passer en mode NINTENDO ?",
                                 "切换到 NINTENDO 模式？" },
    [STR_CONFIRM_REBOOT]     = { "The console will REBOOT now.",
                                 "La consola va a REINICIAR ahora.",
                                 "O console vai REINICIAR agora.",
                                 "La console va REDÉMARRER maintenant.",
                                 "主机将立即重启。" },
    [STR_CONFIRM_RESTART_NEXTENDO] = { "After reboot: connected to Nextendo Network servers.",
                                       "Al reiniciar: conectado a los servidores Nextendo Network.",
                                       "Ao reiniciar: conectado aos servidores Nextendo Network.",
                                       "Au redémarrage : connecté aux serveurs Nextendo Network.",
                                       "重启后：连接到 Nextendo Network 服务器。" },
    [STR_CONFIRM_RESTART_NINTENDO] = { "After reboot: back to official Nintendo servers.",
                                       "Al reiniciar: vuelta a los servidores oficiales Nintendo.",
                                       "Ao reiniciar: volta aos servidores oficiais Nintendo.",
                                       "Au redémarrage : retour aux serveurs officiels Nintendo.",
                                       "重启后：返回 Nintendo 官方服务器。" },
    [STR_CONFIRM_RESTART_NINTENDO_EMU] = { "After reboot: official DNS. Online services will not work.",
                                           "Al reiniciar: DNS oficial. Los servicios en linea no iran.",
                                           "Ao reiniciar: DNS oficial. Os servicos online nao irao.",
                                           "Au redémarrage : DNS officiel. Les services en ligne seront HS.",
                                           "重启后：官方 DNS。在线服务将无法使用。" },
    [STR_CONFIRM_CLOSE_GAMES] = { "Close any running games before confirming.",
                                  "Cierra cualquier juego abierto antes de confirmar.",
                                  "Feche qualquer jogo aberto antes de confirmar.",
                                  "Ferme tout jeu en cours avant de confirmer.",
                                  "请先关闭所有运行中的游戏再确认。" },
    [STR_CONFIRM_A]          = { "A: Confirm", "A: Confirmar", "A: Confirmar", "A : Confirmer",
                                 "A: 确认" },
    [STR_CONFIRM_B]          = { "B: Cancel", "B: Cancelar", "B: Cancelar", "B : Annuler",
                                 "B: 取消" },

    // --- No-emuMMC warnings ---
    [STR_WARN_TITLE]         = { "WARNING: this console has no emuMMC.",
                                 "ATENCION: esta consola no tiene emuMMC.",
                                 "ATENCAO: este console nao tem emuMMC.",
                                 "ATTENTION : cette console n'a pas d'emuMMC.",
                                 "警告：此主机没有 emuMMC。" },
    [STR_WARN_LINE1]         = { "CFW runs on internal memory with your real console ID.",
                                 "El CFW funciona en la memoria interna con tu identificador real.",
                                 "O CFW roda na memoria interna com seu ID real do console.",
                                 "Le CFW tourne sur la mémoire interne avec ton vrai identifiant console.",
                                 "CFW 运行在内置存储上，使用你的真实主机 ID。" },
    [STR_WARN_LINE2]         = { "No identity protection without breaking eShop.",
                                 "No es posible proteger la identidad sin romper eShop.",
                                 "Nao e possivel proteger a identidade sem quebrar o eShop.",
                                 "Aucune protection d'identité possible sans casser l'eShop.",
                                 "无法在不影响 eShop 的情况下保护身份。" },
    [STR_WARN_LINE3]         = { "Going ONLINE on real Nintendo remains at your own risk.",
                                 "Ir EN LINEA al Nintendo real sigue siendo bajo tu riesgo.",
                                 "Ir ONLINE no Nintendo real permanece sob seu risco.",
                                 "Aller EN LIGNE sur le vrai Nintendo reste à tes risques.",
                                 "连接 Nintendo 官方联机风险自担。" },
    [STR_WARN_LINE4]         = { "(Telemetry is still blocked.)",
                                 "(La telemetria sigue bloqueada.)",
                                 "(A telemetria continua bloqueada.)",
                                 "(La télémétrie reste bloquée.)",
                                 "(遥测仍被屏蔽。)" },

    // --- S2 bar (picker screen) ---
    [STR_S2_BAR]             = { "Splatoon 2   -   Install online schedule",
                                 "Splatoon 2   -   Instalar planning en linea",
                                 "Splatoon 2   -   Instalar cronograma online",
                                 "Splatoon 2   -   Installer le planning en ligne",
                                 "Splatoon 2   -   安装在线日程" },

    // --- S2 info screen ---
    [STR_S2_TITLE]           = { "Splatoon 2 online schedule",
                                 "Planning en linea Splatoon 2",
                                 "Cronograma online Splatoon 2",
                                 "Planning en ligne Splatoon 2",
                                 "Splatoon 2 在线日程" },
    [STR_S2_DESC1]           = { "Downloads the rotation schedule (Turf War, Salmon Run, Festivals)",
                                 "Descarga el calendario de modos (Guerra Territorial, Salmon Run, Festivales)",
                                 "Baixa o calendario de modos (Guerra Territorial, Salmon Run, Festivais)",
                                 "Télécharge le calendrier des modes (Guerre Territoriale, Salmon Run, Festivals)",
                                 "下载轮换日程（占地对战、鲑鱼跑、祭典）" },
    [STR_S2_DESC2]           = { "from the Nextendo servers and installs it into Splatoon 2.",
                                 "desde los servidores Nextendo y lo instala en Splatoon 2.",
                                 "dos servidores Nextendo e instala no Splatoon 2.",
                                 "depuis les serveurs Nextendo et l'installe dans Splatoon 2.",
                                 "从 Nextendo 服务器下载并安装到 Splatoon 2。" },
    [STR_S2_DESC3]           = { "Launch Splatoon 2 at least once first. No reboot required.",
                                 "Inicia Splatoon 2 al menos una vez antes. No requiere reinicio.",
                                 "Inicie Splatoon 2 pelo menos uma vez antes. Nao requer reinicializacao.",
                                 "Lance Splatoon 2 au moins une fois avant. Aucun redémarrage requis.",
                                 "请先至少启动一次 Splatoon 2。无需重启。" },
    [STR_S2_DESC4]           = { "Each installation REPLACES the previous schedule.",
                                 "Cada instalacion REEMPLAZA el planning anterior.",
                                 "Cada instalacao SUBSTITUI o cronograma anterior.",
                                 "Chaque installation REMPLACE le planning précédent.",
                                 "每次安装会替换之前的日程。" },
    [STR_S2_A]               = { "A: Install", "A: Instalar", "A: Instalar", "A : Installer",
                                 "A: 安装" },
    [STR_S2_B]               = { "B: Back", "B: Volver", "B: Voltar", "B : Retour",
                                 "B: 返回" },

    // --- Progress screen ---
    [STR_PROGRESS_TITLE]     = { "Installation", "Instalacion", "Instalacao", "Installation",
                                 "安装中" },
    [STR_PROGRESS_WAIT]      = { "Please wait...", "Espere por favor...", "Aguarde por favor...", "Patiente...",
                                 "请稍候..." },

    // --- Result screen ---
    [STR_RESULT_RETURN]      = { "A / B: Return", "A / B: Volver", "A / B: Voltar", "A / B : Retour",
                                 "A / B: 返回" },

    // --- Status messages (main.c) ---
    [STR_STATUS_NEXTENDO_OK]   = { "NEXTENDO mode applied  -  rebooting...",
                                    "Modo NEXTENDO aplicado  -  reiniciando...",
                                    "Modo NEXTENDO aplicado  -  reiniciando...",
                                    "Mode NEXTENDO appliqué  -  redémarrage...",
                                    "NEXTENDO 模式已应用  -  正在重启..." },
    [STR_STATUS_NINTENDO_OK]   = { "NINTENDO mode applied  -  rebooting...",
                                   "Modo NINTENDO aplicado  -  reiniciando...",
                                   "Modo NINTENDO aplicado  -  reiniciando...",
                                   "Mode NINTENDO appliqué  -  redémarrage...",
                                   "NINTENDO 模式已应用  -  正在重启..." },
    [STR_STATUS_REBOOT_FAIL]   = { "Reboot failed",
                                   "Error al reiniciar",
                                   "Falha ao reiniciar",
                                   "Échec du redémarrage",
                                   "重启失败" },
    [STR_STATUS_SD_ERROR]      = { "ERROR: cannot write to SD card",
                                   "ERROR: no se puede escribir en la SD",
                                   "ERRO: nao e possivel escrever no cartao SD",
                                   "ERREUR : écriture sur la SD impossible",
                                   "错误：无法写入 SD 卡" },
    [STR_STATUS_DOWNLOAD_SCHEDULE] = { "Downloading and installing schedule...",
                                       "Descargando e instalando planning...",
                                       "Baixando e instalando cronograma...",
                                       "Téléchargement et installation du planning...",
                                       "正在下载并安装日程..." },
    [STR_STATUS_SCHEDULE_OK]   = { "Schedule installed",
                                   "Planning instalado",
                                   "Cronograma instalado",
                                   "Planning installé",
                                   "日程已安装" },
    [STR_STATUS_SCHEDULE_OK_DESC]  = { "Old schedule replaced. Relaunch Splatoon 2 to apply.",
                                       "Planning anterior reemplazado. Reinicia Splatoon 2 para aplicar.",
                                       "Cronograma anterior substituido. Reinicie Splatoon 2 para aplicar.",
                                       "Ancien planning remplacé. Relance Splatoon 2 pour l'appliquer.",
                                       "旧日程已替换。请重新启动 Splatoon 2 以生效。" },
    [STR_STATUS_NO_SCHEDULE]   = { "No schedule",
                                   "Sin planning",
                                   "Sem cronograma",
                                   "Aucun planning",
                                   "无日程" },
    [STR_STATUS_NO_SCHEDULE_DESC]  = { "Nothing published yet.",
                                       "Nada publicado aun.",
                                       "Nada publicado ainda.",
                                       "Rien de publié pour le moment.",
                                       "尚未发布任何内容。" },
    [STR_STATUS_MOUNT_FAIL]    = { "Save data not found",
                                   "Datos de guardado no encontrados",
                                   "Dados salvos nao encontrados",
                                   "Sauvegarde introuvable",
                                   "未找到存档数据" },
    [STR_STATUS_MOUNT_FAIL_DESC]   = { "Launch Splatoon 2 once, then try again.",
                                       "Inicia Splatoon 2 una vez, luego intenta de nuevo.",
                                       "Inicie Splatoon 2 uma vez, entao tente novamente.",
                                       "Lance Splatoon 2 une fois, puis réessaie.",
                                       "请先启动一次 Splatoon 2，然后重试。" },
    [STR_STATUS_NET_FAIL]      = { "Network error",
                                   "Error de red",
                                   "Erro de rede",
                                   "Erreur réseau",
                                   "网络错误" },
    [STR_STATUS_NET_FAIL_DESC] = { "Download failed (check connection / mode).",
                                   "Fallo la descarga (verifica conexion / modo).",
                                   "Falha no download (verifique conexao / modo).",
                                   "Téléchargement impossible (vérifie la connexion / le mode).",
                                   "下载失败（请检查网络连接/模式）。" },
    [STR_STATUS_WRITE_FAIL]    = { "Write error",
                                   "Error de escritura",
                                   "Erro de gravacao",
                                   "Erreur d'écriture",
                                   "写入错误" },
    [STR_STATUS_WRITE_FAIL_DESC]   = { "Cannot write to save data.",
                                       "No se puede escribir en los datos de guardado.",
                                       "Nao e possivel gravar nos dados salvos.",
                                       "Écriture dans la sauvegarde impossible.",
                                       "无法写入存档数据。" },
    [STR_STATUS_NET_CONNECT]   = { "Server unreachable",
                                   "Servidor inaccesible",
                                   "Servidor inacessivel",
                                   "Serveur inaccessible",
                                   "服务器不可达" },
    [STR_STATUS_NET_CONNECT_DESC] = { "Cannot connect to server (check internet / mode).",
                                      "No se puede conectar al servidor (verifica internet / modo).",
                                      "Nao e possivel conectar ao servidor (verifique internet / modo).",
                                      "Impossible de contacter le serveur (vérifie connexion / mode).",
                                      "无法连接服务器（请检查网络/模式）。" },
    [STR_STATUS_NET_TIMEOUT]   = { "Connection timeout",
                                   "Tiempo de conexion agotado",
                                   "Tempo de conexao esgotado",
                                   "Délai de connexion dépassé",
                                   "连接超时" },
    [STR_STATUS_NET_TIMEOUT_DESC] = { "Server took too long to respond. Try again.",
                                      "El servidor tardo demasiado en responder. Intenta de nuevo.",
                                      "O servidor demorou muito para responder. Tente novamente.",
                                      "Le serveur a mis trop de temps à répondre. Réessaie.",
                                      "服务器响应超时。请重试。" },
    [STR_STATUS_NET_HTTP_ERR]  = { "Server error",
                                   "Error del servidor",
                                   "Erro do servidor",
                                   "Erreur du serveur",
                                   "服务器错误" },
    [STR_STATUS_NET_HTTP_ERR_DESC] = { "Server returned an unexpected response.",
                                       "El servidor devolvio una respuesta inesperada.",
                                       "O servidor retornou uma resposta inesperada.",
                                       "Le serveur a renvoyé une réponse inattendue.",
                                       "服务器返回了意外的响应。" },
    [STR_CHECKING_UPDATE]          = { "Checking for updates...",
                                       "Verificando actualizacion...",
                                       "Verificando atualizacao...",
                                       "Vérification de la mise à jour...",
                                       "正在检查更新..." },
    [STR_STATUS_DOWNLOAD_UPDATE]   = { "Downloading update...",
                                       "Descargando actualizacion...",
                                       "Baixando atualizacao...",
                                       "Téléchargement de la mise à jour...",
                                       "正在下载更新..." },
    [STR_STATUS_INSTALL_UPDATE]    = { "Installing update...",
                                       "Instalando actualizacion...",
                                       "Instalando atualizacao...",
                                       "Installation de la mise à jour...",
                                       "正在安装更新..." },
    [STR_STATUS_UPDATE_OK]     = { "Update installed",
                                   "Actualizacion instalada",
                                   "Atualizacao instalada",
                                   "Mise à jour installée",
                                   "更新已安装" },
    [STR_STATUS_UPDATE_OK_DESC]    = { "CLOSE and relaunch Prelude to apply v%d.%d.%d.",
                                        "CIERRA y reinicia Prelude para aplicar v%d.",
                                        "FECHE e reinicie o Prelude para aplicar v%d.",
                                        "FERME et relance Prelude pour appliquer la v%d.",
                                        "请关闭并重新启动 Prelude 以应用 v%d.%d.%d。" },
    [STR_STATUS_UPDATE_SIZE_FAIL]  = { "Download corrupted",
                                       "Descarga corrupta",
                                       "Download corrompido",
                                       "Téléchargement corrompu",
                                       "下载已损坏" },
    [STR_STATUS_UPDATE_SIZE_FAIL_DESC] = { "Unexpected size. Try again.",
                                           "Tamano inesperado. Intenta de nuevo.",
                                           "Tamanho inesperado. Tente novamente.",
                                           "Taille inattendue. Réessaie.",
                                           "大小异常。请重试。" },
    [STR_STATUS_UPDATE_WRITE_FAIL] = { "Write failed",
                                       "Error de escritura",
                                       "Falha ao escrever",
                                       "Échec d'écriture",
                                       "写入失败" },
    [STR_STATUS_UPDATE_WRITE_FAIL_DESC] = { "Cannot write to SD card.",
                                            "No se puede escribir en la SD.",
                                            "Nao e possivel escrever no cartao SD.",
                                            "Impossible d'écrire sur la carte SD.",
                                            "无法写入 SD 卡。" },
    [STR_STATUS_UPDATE_NET_FAIL]   = { "Network error",
                                       "Error de red",
                                       "Erro de rede",
                                       "Erreur réseau",
                                       "网络错误" },
    [STR_STATUS_UPDATE_NET_FAIL_DESC] = { "Download failed.",
                                          "Fallo la descarga.",
                                          "Falha no download.",
                                          "Téléchargement impossible.",
                                          "下载失败。" },

    // --- Language menu ---
    [STR_LANG_TITLE]        = { "Language", "Idioma", "Idioma", "Langue",
                                "语言" },
    [STR_LANG_EN]           = { "English", "English", "Ingles", "Anglais", "English" },
    [STR_LANG_ES]           = { "Spanish", "Espanol", "Espanhol", "Espagnol", "Espanol" },
    [STR_LANG_PT]           = { "Portuguese", "Portugues", "Portugues", "Portuguais", "Portugues" },
    [STR_LANG_FR]           = { "French", "Frances", "Frances", "Francais", "Francais" },
    [STR_LANG_ZH]           = { "Chinese", "Chino", "Chines", "Chinois",
                                "中文" },
    [STR_LANG_DEFAULT]      = { "(Default)", "(Defecto)", "(Padrao)", "(Défaut)",
                                "(默认)" },
    [STR_LANG_A_SELECT]     = { "A: Select", "A: Elegir", "A: Selecionar", "A : Choisir",
                                "A: 选择" },
    [STR_LANG_B_BACK]       = { "B: Back", "B: Volver", "B: Voltar", "B : Retour",
                                "B: 返回" },

    // --- Update confirmation ---
    [STR_UPD_CONFIRM_TITLE]    = { "Update available",
                                   "Actualizacion disponible",
                                   "Atualizacao disponivel",
                                   "Mise à jour disponible",
                                   "有可用更新" },
    [STR_UPD_CONFIRM_VERSION]  = { "New version: v%d.%d.%d",
                                   "Nueva version: build %d",
                                   "Nova versao: build %d",
                                   "Nouvelle version : build %d",
                                   "新版本：v%d.%d.%d" },
    [STR_UPD_CONFIRM_DESC]    = { "Prelude will download and replace itself.",
                                  "Prelude descargara y se reemplazara a si mismo.",
                                  "Prelude baixara e substituira a si mesmo.",
                                  "Prelude va se télécharger et se remplacer.",
                                  "Prelude 将下载并替换自身。" },
    [STR_UPD_CONFIRM_A]       = { "A: Download and install",
                                  "A: Descargar e instalar",
                                  "A: Baixar e instalar",
                                  "A: Télécharger et installer",
                                  "A: 下载并安装" },
    [STR_UPD_CONFIRM_B]       = { "B: Cancel",
                                   "B: Cancelar",
                                   "B: Cancelar",
                                   "B: Annuler",
                                   "B: 取消" },

    // --- Server switch toast ---
    [STR_TOAST_SERVER_DEFAULT] = { "Server: VPS (51.178.29.194)",
                                   "Servidor: VPS (51.178.29.194)",
                                   "Servidor: VPS (51.178.29.194)",
                                   "Serveur : VPS (51.178.29.194)",
                                   "服务器: VPS (51.178.29.194)" },
    [STR_TOAST_SERVER_ALT]     = { "Server: Local (3.135.232.168)",
                                   "Servidor: Local (3.135.232.168)",
                                   "Servidor: Local (3.135.232.168)",
                                   "Serveur : Local (3.135.232.168)",
                                   "服务器: Local (3.135.232.168)" },

    // --- Flag bar ---
    [STR_FLAG_BAR]      = { "MK8D   -   Country Flag",
                            "MK8D   -   Bandera de pais",
                            "MK8D   -   Bandeira do pais",
                            "MK8D   -   Drapeau du pays",
                            "MK8D   -   国家/地区旗帜" },
    [STR_MODS_TITLE]    = { "Update your installed mods?",
                            "Actualizar los mods instalados?",
                            "Atualizar os mods instalados?",
                            "Mettre a jour les mods installes ?",
                            "更新已安装的本NRO模组？" },
    [STR_MODS_BODY1]    = { "This Prelude carries newer versions than the ones on your SD card.",
                            "Este Prelude trae versiones mas nuevas que las de tu tarjeta SD.",
                            "Este Prelude traz versoes mais novas que as do seu cartao SD.",
                            "Ce Prelude embarque des versions plus recentes que celles de votre carte SD.",
                            "此 Prelude 包含比你 SD 卡上更新的版本。" },
    [STR_MODS_BODY2]    = { "A: update them   B: keep what you have",
                            "A: actualizarlos   B: dejarlos como estan",
                            "A: atualizar   B: manter como esta",
                            "A : mettre a jour   B : garder tel quel",
                            "A: 更新   B: 保留现有版本" },
    [STR_MODS_UPDATED]  = { "Mods updated", "Mods actualizados", "Mods atualizados", "Mods mis a jour",
                            "模组已更新" },
    [STR_MODS_FAILED]   = { "Could not update the mods",
                            "No se pudieron actualizar los mods",
                            "Nao foi possivel atualizar os mods",
                            "Impossible de mettre a jour les mods",
                            "无法更新模组" },
    [STR_BACKUP_TITLE]  = { "Back up your current DNS files?",
                            "Copia de seguridad de tus DNS?",
                            "Fazer backup dos seus DNS?",
                            "Sauvegarder vos fichiers DNS ?",
                            "备份当前 DNS 文件？" },
    [STR_BACKUP_BODY1]  = { "Prelude overwrites atmosphere/hosts (sysmmc.txt, emummc.txt).",
                            "Prelude sobrescribe atmosphere/hosts (sysmmc.txt, emummc.txt).",
                            "O Prelude sobrescreve atmosphere/hosts (sysmmc.txt, emummc.txt).",
                            "Prelude ecrase atmosphere/hosts (sysmmc.txt, emummc.txt).",
                            "Prelude 会覆盖 atmosphere/hosts (sysmmc.txt, emummc.txt)。" },
    [STR_BACKUP_BODY2]  = { "A copy is kept in switch/prelude_hosts_backup.",
                            "Se guarda una copia en switch/prelude_hosts_backup.",
                            "Uma copia fica em switch/prelude_hosts_backup.",
                            "Une copie est gardee dans switch/prelude_hosts_backup.",
                            "备份保存在 switch/prelude_hosts_backup。" },
    [STR_USEBAK_TITLE]  = { "Use that backup for Nintendo mode?",
                            "Usar esa copia en modo Nintendo?",
                            "Usar esse backup no modo Nintendo?",
                            "Utiliser cette copie en mode Nintendo ?",
                            "在 Nintendo 模式下使用该备份？" },
    [STR_USEBAK_BODY1]  = { "Nintendo mode deletes the DNS files. It can restore yours instead.",
                            "El modo Nintendo borra los DNS. Puede restaurar los tuyos.",
                            "O modo Nintendo apaga os DNS. Pode restaurar os seus.",
                            "Le mode Nintendo supprime les DNS. Il peut remettre les votres.",
                            "Nintendo 模式会删除 DNS 文件。可以改为恢复你的备份。" },
    [STR_USEBAK_BODY2]  = { "Choose No for untouched official servers.",
                            "Elige No para servidores oficiales sin nada.",
                            "Escolha Nao para servidores oficiais puros.",
                            "Choisissez Non pour des serveurs officiels purs.",
                            "选择「否」则使用纯净的官方服务器。" },
    [STR_ASK_A_YES]     = { "A: Yes", "A: Si", "A: Sim", "A : Oui",
                            "A: 是" },
    [STR_ASK_B_NO]      = { "B: No",  "B: No", "B: Nao", "B : Non",
                            "B: 否" },
    [STR_BACKUP_SAVED]  = { "Backup saved.", "Copia guardada.", "Backup salvo.", "Copie enregistree.",
                            "备份已保存。" },
    [STR_BACKUP_NONE]   = { "Nothing to back up.", "No hay nada que copiar.",
                            "Nada para salvar.", "Rien a sauvegarder.",
                            "没有可备份的内容。" },
    [STR_FLAG_BAR_SET]  = { "MK8D   -   Flag: %s",
                            "MK8D   -   Bandera: %s",
                            "MK8D   -   Bandeira: %s",
                            "MK8D   -   Drapeau : %s",
                            "MK8D   -   旗帜: %s" },
    [STR_DESC_FLAG]     = { "Install a country flag for MK8D online play. Other players will see it.",
                            "Instala una bandera de pais para MK8D online. Los demas jugadores la veran.",
                            "Instala uma bandeira para MK8D online. Os outros jogadores vao ve-la.",
                            "Installe un drapeau national pour MK8D en ligne. Les autres joueurs le voient.",
                            "为马车8联机安装国家/地区旗帜，注意游戏没有中国相关旗帜，建议统一选择CH相互标识下吧" },
    [STR_HELP_FLAG]     = { "A: open   < >: change   B: quit",
                            "A: abrir   < >: cambiar   B: salir",
                            "A: abrir   < >: mudar   B: sair",
                            "A : ouvrir   < > : changer   B : quitter",
                            "A: 打开   < >: 切换   B: 退出" },

    // --- Flag menu ---
    [STR_FLAG_MENU_TITLE] = { "MK8D Country Flag", "Bandera de pais MK8D",
                              "Bandeira do pais MK8D", "Drapeau du pays MK8D",
                              "马车8 国家/地区旗帜" },
    [STR_FLAG_NONE]       = { "(none installed)", "(ninguna instalada)",
                              "(nenhuma instalada)", "(aucun installe)",
                              "(未安装)" },
    [STR_FLAG_INSTALLED]  = { "INSTALLED", "INSTALADA", "INSTALADA", "INSTALLE",
                              "已安装" },
    [STR_FLAG_A]          = { "A: Install", "A: Instalar", "A: Instalar", "A : Installer",
                              "A: 安装" },
    [STR_FLAG_B]          = { "B: Back", "B: Volver", "B: Voltar", "B : Retour",
                              "B: 返回" },

    // --- Flag progress / result ---
    [STR_STATUS_DOWNLOAD_FLAG]      = { "Downloading flag...",
                                        "Descargando bandera...",
                                        "Baixando bandeira...",
                                        "Telechargement du drapeau...",
                                        "正在下载旗帜..." },
    [STR_STATUS_FLAG_OK]            = { "Flag installed",
                                        "Bandera instalada",
                                        "Bandeira instalada",
                                        "Drapeau installe",
                                        "旗帜已安装" },
    [STR_STATUS_FLAG_OK_DESC]       = { "Restart MK8D to apply the new country.",
                                        "Reinicia MK8D para aplicar el nuevo pais.",
                                        "Reinicie MK8D para aplicar o novo pais.",
                                        "Redemarrer MK8D pour appliquer le nouveau pays.",
                                        "重启 MK8D 以应用新国家/地区。" },
    [STR_STATUS_FLAG_NET_FAIL]      = { "Network error",
                                        "Error de red",
                                        "Erro de rede",
                                        "Erreur reseau",
                                        "网络错误" },
    [STR_STATUS_FLAG_NET_FAIL_DESC] = { "Could not download flag. Check connection.",
                                        "No se pudo descargar la bandera. Verifica la conexion.",
                                        "Nao foi possivel baixar a bandeira. Verifique a conexao.",
                                        "Impossible de telecharger le drapeau. Verifier la connexion.",
                                        "无法下载旗帜。请检查网络连接。" },
    [STR_STATUS_FLAG_WRITE_FAIL]      = { "Write error",
                                          "Error de escritura",
                                          "Erro de gravacao",
                                          "Erreur d'ecriture",
                                          "写入错误" },
    [STR_STATUS_FLAG_WRITE_FAIL_DESC] = { "Cannot write to SD card.",
                                          "No se puede escribir en la SD.",
                                          "Nao e possivel gravar no cartao SD.",
                                          "Impossible d'ecrire sur la carte SD.",
                                          "无法写入 SD 卡。" },

    // --- Nouveau cromo : rail + barre de boutons. Volontairement courts —
    //     une entree de rail ou un libelle de bouton se lit d'un coup d'oeil,
    //     pas en phrase. ---
    [STR_RAIL_MODE]   = { "Mode",       "Modo",       "Modo",       "Mode",       "模式" },
    [STR_RAIL_S2]     = { "Splatoon 2", "Splatoon 2", "Splatoon 2", "Splatoon 2", "Splatoon 2" },
    [STR_RAIL_FLAG]   = { "Country",    "Pais",       "Pais",       "Pays",       "国家" },
    [STR_RAIL_SSBU]   = { "Smash",      "Smash",      "Smash",      "Smash",      "Smash" },
    [STR_RAIL_S3]     = { "Splatoon 3", "Splatoon 3", "Splatoon 3", "Splatoon 3", "Splatoon 3" },
    [STR_SMB35SP]      = { "Special Battle", "Batalla Especial", "Batalha Especial", "Bataille Speciale",
                           "特殊对战" },
    [STR_SMB35SP_ON]   = { "Installed. The normal 35-player battle is now a Special Battle.",
                           "Instalada. La batalla normal a 35 es ahora una Batalla Especial.",
                           "Instalada. A batalha normal de 35 e agora uma Batalha Especial.",
                           "Installee. La bataille a 35 ordinaire est devenue une Bataille Speciale.",
                           "已安装。普通的 35 人对战现在变为特殊对战。" },
    [STR_SMB35SP_OFF]  = { "Not installed.",
                           "No instalada.",
                           "Nao instalada.",
                           "Non installee.",
                           "未安装。" },
    [STR_SMB35SP_WARN] = { "Replaces the normal battle, it does not add a mode. Needs game 1.0.2 and the console clock set.",
                           "Sustituye a la batalla normal, no anade un modo. Necesita el juego 1.0.2 y la hora de la consola al dia.",
                           "Substitui a batalha normal, nao adiciona um modo. Precisa do jogo 1.0.2 e do relogio do console certo.",
                           "Remplace la bataille ordinaire, elle n'ajoute pas un mode. Exige le jeu 1.0.2 et l'horloge a jour.",
                           "替换普通对战，而非新增模式。需要游戏 1.0.2 版本并校准主机时钟。" },
    [STR_SMB35SP_DONE] = { "Special Battle installed", "Batalla Especial instalada", "Batalha Especial instalada", "Bataille Speciale installee",
                           "特殊对战已安装" },
    [STR_SMB35SP_GONE] = { "Special Battle removed", "Batalla Especial desinstalada", "Batalha Especial desinstalada", "Bataille Speciale retiree",
                           "特殊对战已移除" },
    [STR_RAIL_SMB35]  = { "Mario 35",   "Mario 35",   "Mario 35",   "Mario 35",   "Mario 35" },
    [STR_DESC_SMB35]  = { "Downloads the current Special Battle event and installs it into Super Mario Bros. 35.",
                          "Descarga la Batalla Especial actual y la instala en Super Mario Bros. 35.",
                          "Baixa a Batalha Especial atual e instala em Super Mario Bros. 35.",
                          "Telecharge la Bataille Speciale en cours et l'installe dans Super Mario Bros. 35.",
                          "下载当前的特殊对战活动并安装到 Super Mario Bros. 35 中。" },
    [STR_STATUS_DOWNLOAD_SMB35] = { "Downloading and installing event...",
                          "Descargando e instalando el evento...",
                          "Baixando e instalando o evento...",
                          "Telechargement et installation de l'evenement...",
                          "正在下载并安装活动..." },
    [STR_STATUS_SMB35_OK] = { "Event installed", "Evento instalado", "Evento instalado", "Evenement installe",
                          "活动已安装" },
    [STR_STATUS_SMB35_OK_DESC] = { "Relaunch Super Mario Bros. 35 to apply.",
                          "Reinicia Super Mario Bros. 35 para aplicarlo.",
                          "Reinicie Super Mario Bros. 35 para aplicar.",
                          "Relancez Super Mario Bros. 35 pour appliquer.",
                          "重启 Super Mario Bros. 35 以应用。" },
    [STR_STATUS_NO_EVENT] = { "No event", "Sin evento", "Sem evento", "Aucun evenement",
                          "无活动" },
    [STR_STATUS_NO_EVENT_DESC] = { "There is no Special Battle published right now.",
                          "Ahora mismo no hay ninguna Batalla Especial publicada.",
                          "Nao ha nenhuma Batalha Especial publicada agora.",
                          "Aucune Bataille Speciale n'est publiee pour le moment.",
                          "目前没有发布任何特殊对战活动。" },
    [STR_RAIL_LANG]   = { "Language",   "Idioma",     "Idioma",     "Langue",     "语言" },

    [STR_S3_TITLE]    = { "Splatoon 3 patches",
                          "Parches de Splatoon 3",
                          "Correcoes de Splatoon 3",
                          "Correctifs Splatoon 3",
                          "Splatoon 3 补丁" },
    [STR_S3_OK]       = { "Installed and up to date (%d files).",
                          "Instalados y al dia (%d ficheros).",
                          "Instalados e atualizados (%d ficheiros).",
                          "Installes et a jour (%d fichiers).",
                          "已安装且为最新版本 (%d 个文件)。" },
    [STR_S3_STALE]    = { "Card has %d, this version ships %d - out of date.",
                          "La tarjeta tiene %d, esta version trae %d - desactualizados.",
                          "O cartao tem %d, esta versao traz %d - desatualizados.",
                          "La carte en a %d, cette version en livre %d - perimes.",
                          "卡上有 %d 个，当前版本包含 %d 个 - 已过时。" },
    [STR_S3_MISSING]  = { "Not on the SD card. Splatoon 3 will fail with 2122-2403.",
                          "No estan en la tarjeta. Splatoon 3 fallara con 2122-2403.",
                          "Nao estao no cartao. Splatoon 3 vai falhar com 2122-2403.",
                          "Absents de la carte. Splatoon 3 echouera avec 2122-2403.",
                          "不在 SD 卡上。Splatoon 3 将报错 2122-2403。" },
    [STR_S3_FIX]      = { "Fix: apply Nextendo mode, then reboot.",
                          "Solucion: aplica el modo Nextendo y reinicia.",
                          "Solucao: aplique o modo Nextendo e reinicie.",
                          "Solution : applique le mode Nextendo, puis redemarre.",
                          "修复：应用 Nextendo 模式，然后重启。" },
    [STR_S3_DNS_OFF]  = { "DNS redirect is OFF - nothing reaches our servers.",
                          "La redireccion DNS esta APAGADA - no llega nada a nuestros servidores.",
                          "O redirecionamento DNS esta DESLIGADO - nada chega aos servidores.",
                          "La redirection DNS est COUPEE - rien n'atteint nos serveurs.",
                          "DNS 重定向已关闭 - 流量无法到达我们的服务器。" },
    [STR_S3_NINTENDO] = { "You are in Nintendo mode: patches are removed on purpose.",
                          "Estas en modo Nintendo: los parches se quitan a proposito.",
                          "Voce esta no modo Nintendo: as correcoes sao removidas de proposito.",
                          "Vous etes en mode Nintendo : les correctifs sont retires expres.",
                          "你当前在 Nintendo 模式：补丁已被故意移除。" },
    [STR_S3_WHERE]    = { "On the card: atmosphere/exefs_patches/s3certbypass",
                          "En la tarjeta: atmosphere/exefs_patches/s3certbypass",
                          "No cartao: atmosphere/exefs_patches/s3certbypass",
                          "Sur la carte : atmosphere/exefs_patches/s3certbypass",
                          "位置：atmosphere/exefs_patches/s3certbypass" },
    [STR_S3_LIMIT]    = { "This checks the files are there, not that the game accepted them.",
                          "Esto comprueba que los ficheros estan, no que el juego los aceptara.",
                          "Isto verifica que os ficheiros estao la, nao que o jogo os aceitou.",
                          "Ceci verifie leur presence, pas qu'ils aient ete appliques.",
                          "此检查仅确认文件存在，不能保证游戏已接受。" },
    [STR_S3_INSTALL]  = { "Install patches",
                          "Instalar parches",
                          "Instalar correcoes",
                          "Installer les correctifs",
                          "安装补丁" },
    [STR_S3_REINSTALL]= { "Reinstall patches",
                          "Reinstalar parches",
                          "Reinstalar correcoes",
                          "Reinstaller les correctifs",
                          "重新安装补丁" },
    [STR_S3_REINSTALL_SUB] = { "Rewrites them to the SD card. Reboot afterwards.",
                          "Los reescribe en la tarjeta. Reinicia despues.",
                          "Reescreve-os no cartao. Reinicie depois.",
                          "Les reecrit sur la carte. Redemarrez ensuite.",
                          "重新写入 SD 卡。之后请重启。" },
    [STR_S3_DONE]     = { "Patches written. Reboot the console.",
                          "Parches escritos. Reinicia la consola.",
                          "Correcoes escritas. Reinicie o console.",
                          "Correctifs ecrits. Redemarrez la console.",
                          "补丁已写入。请重启主机。" },
    [STR_S3_VERSION]  = { "Avoid updating the game: a new version needs new patches.",
                          "Evita actualizar el juego: una version nueva necesita parches nuevos.",
                          "Evite atualizar o jogo: uma versao nova precisa de correcoes novas.",
                          "Evitez de mettre le jeu a jour : une version neuve exige d'autres correctifs.",
                          "请勿更新游戏：新版本需要新补丁。" },
    [STR_BADGE_ACTIVE]= { "Active",     "Activo",     "Ativo",      "Actif",
                          "活跃" },
    [STR_HINT_APPLY]  = { "Apply",      "Aplicar",    "Aplicar",    "Appliquer",
                          "应用" },
    [STR_HINT_EXIT]   = { "Exit",       "Salir",      "Sair",       "Quitter",
                          "退出" },
    [STR_HINT_BACK]   = { "Back",       "Volver",     "Voltar",     "Retour",
                          "返回" },
    [STR_HINT_CHANGE] = { "Change",     "Cambiar",    "Alterar",    "Modifier",
                          "更换" },
    [STR_HINT_OPEN]   = { "Open",       "Abrir",      "Abrir",      "Ouvrir",
                          "打开" },
    [STR_HINT_UPDATE] = { "Update",     "Actualizar", "Atualizar",  "Mettre à jour",
                          "更新" },
    // --- Section SSBU ---
    [STR_S2_TITLE_MOD]       = { "Mod", "Mod", "Mod", "Mod", "Mod" },
    [STR_SSBU_APPLIES]       = { "Applies on reboot in Nextendo mode",
                                 "Se aplica al reiniciar en modo Nextendo",
                                 "Aplica ao reiniciar no modo Nextendo",
                                 "S'applique au redemarrage en mode Nextendo",
                                 "在 Nextendo 模式下重启后生效" },
    [STR_SSBU_INSTALLED]     = { "Installed", "Instalado", "Instalado", "Installe",
                                 "已安装" },
    [STR_SSBU_NOT_INSTALLED] = { "Not installed", "No instalado", "Nao instalado", "Non installe",
                                 "未安装" },
    [STR_SSBU_INSTALL]       = { "Install", "Instalar", "Instalar", "Installer",
                                 "安装" },
    [STR_SSBU_UNINSTALL]     = { "Uninstall", "Desinstalar", "Desinstalar", "Desinstaller",
                                 "卸载" },
    [STR_SSBU_OC]            = { "Mod overclock", "Overclock del mod", "Overclock do mod", "Overclock du mod",
                                 "Mod 超频" },
    [STR_SSBU_OC_ON_DESC]    = { "Turn it off if you use Horizon OC or sys-clk",
                                 "Desactivalo si usas Horizon OC o sys-clk",
                                 "Desative se voce usa Horizon OC ou sys-clk",
                                 "Coupe-le si tu utilises Horizon OC ou sys-clk",
                                 "如果你使用 Horizon OC 或 sys-clk，请关闭此选项" },
    [STR_SSBU_OC_OFF_DESC]   = { "Compatible with Horizon OC / sys-clk",
                                 "Compatible con Horizon OC / sys-clk",
                                 "Compativel com Horizon OC / sys-clk",
                                 "Compatible avec Horizon OC / sys-clk",
                                 "与 Horizon OC / sys-clk 兼容" },
};

// ============================================================

void lang_init(void) {
    FILE *f = fopen(LANG_PATH, "rb");
    if (!f) { g_lang = LANG_EN; return; }
    int c = fgetc(f);
    fclose(f);
    if (c == 'E') g_lang = LANG_EN;
    else if (c == 'S') g_lang = LANG_ES;
    else if (c == 'P') g_lang = LANG_PT;
    else if (c == 'F') g_lang = LANG_FR;
    else if (c == 'Z') g_lang = LANG_ZH;
    else g_lang = LANG_EN;
}

void lang_save(void) {
    char ch = 'E';
    if (g_lang == LANG_ES) ch = 'S';
    else if (g_lang == LANG_PT) ch = 'P';
    else if (g_lang == LANG_FR) ch = 'F';
    else if (g_lang == LANG_ZH) ch = 'Z';
    // else LANG_EN -> 'E'
    FILE *f = fopen(LANG_PATH, "wb");
    if (!f) {
        mkdir("sdmc:/switch", 0777);
        f = fopen(LANG_PATH, "wb");
    }
    if (f) { fputc(ch, f); fclose(f); }
    fsdevCommitDevice("sdmc");
}

const char *lang_str(StringID id) {
    if (id < 0 || id >= STR_COUNT) return "?";
    if (g_lang < 0 || g_lang >= (int)(sizeof(s_strings[0]) / sizeof(s_strings[0][0])))
        g_lang = LANG_EN;
    return s_strings[id][g_lang];
}
